jQuery NiceForms
===========================

Introduction
---------------------------

The jQuery NiceForms is a adaptation created by [Fernando Jorge Mota](http://about.me/fjorgemota/) of the original NiceForms 2.0, created by [Lucian Slatineanu](http://www.emblematiq.com/projects/niceforms/). The use is now provided by jQuery, with a simple API as showed in file [demo.html](http://dl.dropbox.com/u/17820466/jQuery.niceforms/demo.html).

Good use!

Demo
---------------------------

[It's here](http://dl.dropbox.com/u/17820466/jQuery.niceforms/demo.html).


Bugs 
---------------------------

This versions have bugs: It doesn't is showed correctly in IE and cannot be directly integrated in the HTML (as a copy of the DOM generated by the system). The 
next versions can correct this, with the help of you, developer.

